coffeemarket/accounts/urls.py
from django.conf.urls import handler404
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # ユーザ関連
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user/info/', views.UserInfo.as_view(), name='userInfo'),
]

coffeemarket/coffeemarket/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('silk/', include('silk.urls', namespace='silk')),
    path('admin/', admin.site.urls),
    path('market/', include('market.urls')),
    path('accounts/', include('accounts.urls')),
]

coffeemarket/market/urls.py
from django.conf.urls import handler404
from django.contrib.auth.views import LoginView, LogoutView
from django.http import request
from django.urls import path
from .views import bean_views, cart_views, payment_views, user_views

app_name = 'market'

urlpatterns = [
    # coffee関連
    path('newbeans/', bean_views.InsertBeansView.as_view(), name='insertBeans'),
    path('newplace/', bean_views.InsertPlaceView.as_view(), name='insertPlace'),
    path('bean/list/', bean_views.Top.as_view(), name='top'),
    path('bean/<int:pk>/', cart_views.BeanDetail.as_view(), name='beanDetail'),
    path('bean/list/filter/<int:pk>/', bean_views.PlaceFilterBeanList.as_view(), name='filterBeanList'),
    path('user/cart/', cart_views.CartInfoList.as_view(), name='cartInfo'),
    path('user/cart/buying/', payment_views.BuyingProcessView.as_view(), name='buyingProcess'),
    path('user/cart/buying/error/', payment_views.BuyingErrorView.as_view(), name='buyingError'),
    path('user/cart/buying/success/', payment_views.BuyingSuccessView.as_view(), name='buyingSuccess'),
    path('user/cart/history/', payment_views.PurchaseView.as_view(), name='purchaseHistory'),
    path('user/cart/history/<int:pk>', payment_views.PurchaseHistoryDetailView.as_view(), name='purchaseHistoryDetail'),
    path('user/', user_views.UserInfoView.as_view(), name='user'),
    # path('cart/', views.InsertCartView.as_view(), name='insertCart'),
]

coffeemarket/market/models.py
from django.db import models
from django.contrib.auth.models import User

# PlaceCategory
from django.db.models import UniqueConstraint
from django.utils import timezone


class PlaceCategory(models.Model):
    # id
    place = models.CharField(max_length=25, unique=True)

    def __str__(self):
        return self.place


# CoffeeBeansInfo
class CoffeeBeans(models.Model):
    # id
    beans_name = models.CharField(max_length=25)
    price = models.IntegerField(null=True, blank=True)
    # 登録日付 **更新日付はauto_now
    create_date = models.DateTimeField(auto_now_add=True)
    stock = models.IntegerField()
    # 説明文
    beans_description = models.CharField(max_length=500, null=True, blank=True)
    # 外部キー制約
    place_category = models.ForeignKey(PlaceCategory, null=True, blank=True, on_delete=models.CASCADE)
    # 画像保存先


class BeansImage(models.Model):
    beans_image = models.ImageField(
        upload_to='market/', null=True, blank=True,
    )
    coffee_beans = models.ForeignKey(CoffeeBeans,  on_delete=models.CASCADE)


# now CartInfo
class CartInfo(models.Model):
    # id
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    coffee_beans = models.ForeignKey(CoffeeBeans, on_delete=models.CASCADE)
    volume = models.IntegerField()

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'coffee_beans'], name='unique_cart')
        ]

    # ユニーク制約 validation用
    @classmethod
    def check_unique_constrains(cls, user: User, coffee_beans_pk: CoffeeBeans.pk) -> bool:
        return cls.objects.filter(user=user, coffee_beans_id=coffee_beans_pk).exists()


# PaymentStyle
class PaymentMethod(models.Model):
    # id
    payment_method = models.CharField(max_length=25)


# CustomerPurchaseHistry
class PurchaseHistory(models.Model):
    user_name = models.ForeignKey(User, on_delete=models.CASCADE)
    total_price = models.IntegerField(null=True, blank=True)
    payment_code = models.ForeignKey(PaymentMethod, on_delete=models.CASCADE)
    buy_date = models.DateTimeField(default=timezone.now)

    class Meta:
        unique_together = ('id', 'user_name')


# CustomerPurchaseDetail !!! Django Compound primary key not supported!!
class PurchaseDetail(models.Model):
    purchase_code = models.ForeignKey(PurchaseHistory, on_delete=models.CASCADE)
    beans_code = models.ForeignKey(CoffeeBeans, on_delete=models.CASCADE)
    selling_price = models.IntegerField()
    volume = models.IntegerField()

coffeemarket/market/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from .models import CoffeeBeans, PlaceCategory, CartInfo


# 珈琲追加用form
class InsertBeans(forms.ModelForm):
    class Meta:
        model = CoffeeBeans
        fields = ('beans_name', 'place_category', 'price', 'stock', 'beans_description')
        labels = {
            'beans_name': '豆名',
            'place': '採取地',
            'price': '値段',
            'stock': '在庫数',
            'beans_description': '商品説明'
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['beans_name'].widget.attrs['class'] = 'form-control'
        self.fields['place_category'].widget.attrs['class'] = 'form-control'
        self.fields['price'].widget.attrs['class'] = 'form-control'
        self.fields['stock'].widget.attrs['class'] = 'form-control'
        self.fields['beans_description'].widget.attrs['class'] = 'form-control'


# 産地登録用form
class InsertPlace(forms.ModelForm):
    class Meta:
        model = PlaceCategory
        fields = {'place'}
        labels = {
            'insert_place': '採取地'
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['place'].widget.attrs['class'] = 'form-control'


class InsertCart(forms.ModelForm):
    class Meta:
        model = CartInfo
        fields = ('user', 'coffee_beans', 'volume')
        labels = {
            'user': 'user',
            'coffee_beans': 'id',
            'volume': '数量',
        }
        widgets = {
            'user': forms.HiddenInput(),
            'coffee_beans': forms.HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['volume'].widget.attrs['class'] = 'form-control'


class BeanVolume(forms.Form):

    volume = forms.IntegerField(
        label='数量',
        max_value=5,
        min_value=1
    )

coffeemarket/market/views/bean_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.utils.http import urlencode
from django.views import generic, View

from ..forms import InsertBeans, InsertPlace
from ..models import CoffeeBeans, PlaceCategory, CartInfo, PurchaseHistory, PaymentMethod, PurchaseDetail


# 珈琲豆追加view
# PermissionRequiredMixin アクセス制御 permission_required <app_name> <code_name>
class InsertBeansView(PermissionRequiredMixin, generic.CreateView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        message = self.request.GET.get('msg')
        if message is not None:
            context['msg'] = '入力された産地は既に追加されています。'
        return context

    model = CoffeeBeans
    form_class = InsertBeans
    permission_required = ('market.can_add',)
    template_name = "coffeebeans_form.html"
    success_url = reverse_lazy('market:top')


# 地域登録 テンプレート側のnameをInsertPlaceのfield名と合わせる
class InsertPlaceView(View):

    def post(self, *args, **kwargs):
        redirect_url = reverse('market:insertBeans')
        insert_place = InsertPlace(self.request.POST)
        # 登録

        if insert_place.is_valid():
            insert_place.save()
        else:
            query_string = urlencode({'msg': 'error'})
        redirect_url = '{}?{}'.format(redirect_url, query_string)
        return redirect(redirect_url)


# 珈琲豆一覧
class Top(generic.ListView):
    model = CoffeeBeans
    context_object_name = 'coffee_beans'
    template_name = 'top.html'


# (産地フィルター）珈琲豆一覧
class PlaceFilterBeanList(generic.ListView):
    model = CoffeeBeans
    context_object_name = 'coffee_beans'
    template_name = 'top.html'

    def get_queryset(self):
        # aタグのpk取得・絞り込み
        place = self.kwargs['pk']
        return CoffeeBeans.objects.filter(place_category=place)

coffeemarket/market/views/cart_views.py
# 豆詳細　けん　カート追加処理
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.views.generic import TemplateView

from ..forms import InsertCart
from ..models import CoffeeBeans, CartInfo


class BeanDetail(TemplateView):
    template_name = 'coffeebean_detail.html'

    # initialで

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        bean_id = self.kwargs['pk']
        coffee_beans = get_object_or_404(CoffeeBeans, id=bean_id)
        insert_cart = InsertCart
        context['coffee_bean'] = coffee_beans
        context['insert_cart'] = insert_cart
        return context

    def post(self, *args, **kwargs):
        context = self.get_context_data()
        bean_id = self.kwargs['pk']
        user = self.request.user
        # coffee_beans = get_object_or_404(CoffeeBeans, id=bean_id)
        volume = self.request.POST.get('volume')

        # method unique_exists() validate
        if CartInfo.check_unique_constrains(user, bean_id):
            context['msg'] = 'すでにカート内に登録されています。'

        else:
            context['msg'] = 'カートへの追加完了'
            cart_info = CartInfo(user=user, coffee_beans_id=bean_id, volume=volume)
            cart_info.save()

        return render(self.request, self.template_name, context)
        # CartInfo.objects.create(user=self.request.user, coffee_beans=coffee_beans, volume=volume)


# カート内情報閲覧
class CartInfoList(LoginRequiredMixin, generic.TemplateView):
    template_name = 'cart_info.html'
    login_url = '/accounts/login/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        user = self.request.user
        context['cart_info_list'] = CartInfo.objects.select_related('coffee_beans').filter(user=user)
        context['public_key'] = settings.STRIPE_PUBLIC_KEY
        return context

coffeemarket/market/views/payment_views.py
import stripe
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.utils import timezone
from django.views import generic

from ..models import PurchaseDetail, CartInfo, PurchaseHistory


# 購入処理
def savePurchaseDetail(purchase_history_pk, cart_info_list):
    for cart_info in cart_info_list:
        PurchaseDetail.objects.create(
            purchase_code_id=purchase_history_pk, beans_code_id=cart_info.coffee_beans.pk,
            selling_price=cart_info.coffee_beans.price, volume=cart_info.volume
        )


def sumTotalPrice(cart_info_list):
    total_price = 0
    for cart_info in cart_info_list:
        total_price += cart_info.coffee_beans.price * cart_info.volume
    return total_price


class BuyingProcessView(generic.TemplateView):

    def post(self, *args, **kwargs):
        user = self.request.user
        cart_info_list = CartInfo.objects.filter(user=user)
        token = self.request.POST['stripeToken']
        # total_price calculation
        total_price = sumTotalPrice(cart_info_list)
        try:
            charge = stripe.Charge.create(
                amount=total_price,
                currency='jpy',
                source=token,
                description='珈琲豆売上',
                api_key=settings.STRIPE_SECRET_KEY
            )
        except stripe.error.CardError as e:
            return redirect('market:buyingError')
        except Exception as e:
            # 重大なエラー (APIの仕様変更等,　エラーの範囲が広すぎるかも。
            return redirect('market:buyingError')

        else:
            # 購入履歴に保存
            buy_date = timezone.now()
            PurchaseHistory.objects.create(
                user_name=user, total_price=total_price, payment_code_id=1, buy_date=buy_date
            )
            purchase_history_pk = \
                PurchaseHistory.objects.filter(user_name=user, buy_date=buy_date).values_list('id', flat=True)

            if len(purchase_history_pk) != 1:
                print(purchase_history_pk)
                print("err!")
            else:
                savePurchaseDetail(purchase_history_pk[0], cart_info_list)
            return redirect('market:buyingSuccess')


class PurchaseView(LoginRequiredMixin, generic.ListView):
    context_object_name = 'purchase_historys'
    template_name = 'purchase_history.html'

    def get_queryset(self):
        user = self.request.user
        query_set = PurchaseHistory.objects.filter(user_name=user)
        return query_set


class PurchaseHistoryDetailView(LoginRequiredMixin, generic.ListView):
    context_object_name = 'purchase_details'
    template_name = 'purchase_detail.html'

    def get_queryset(self):
        user = self.request.user
        purchase_id = self.kwargs['pk']
        query_set = \
            PurchaseDetail.objects.select_related(
                'beans_code', 'purchase_code'
            ).filter(
                purchase_code_id=purchase_id, purchase_code__user_name=user
            )
        return query_set

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        purchase_id = self.kwargs['pk']
        context['payment_name'] = PurchaseHistory.objects.values_list(
            'payment_code__payment_method', flat=True).get(id=purchase_id)

        return context


# 決済エラー
class BuyingErrorView(generic.TemplateView):
    template_name = 'buying_error.html'


# 決済完了
class BuyingSuccessView(generic.TemplateView):
    template_name = 'buying_success.html'

coffeemarket/market/views/user_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic


class UserInfoView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'user_info.html'
    login_url = '/accounts/login/'

coffeemarket/market/templates/bad.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>失敗</title>
</head>
<body>
<p>{{ message }}</p>
</body>
</html>

coffeemarket/market/templates/base.html
<!doctype html>
<html lang="ja">
  <head>
    <title>market</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">  </head>
  <body>
  {% load market_tags %}
  <h1 class="text-center my-4"><a href="{% url 'market:top' %}" class="text text-secondary">コーヒーマーケット</a></h1>
  <header>
      <div class="container mb-4 p-0">
          <div class="row">
              <div class="col-md-10">{% place_category_links %}</div>
              {% if user.is_authenticated %}
                <a href="{% url 'market:cartInfo' %}" class="pt-2 mr- btn btn-outline-success float-right mx-auto">カート</a>
                <a href="{% url 'market:user' %}" class="pt-2 mr-0 btn btn-outline-success float-right mx-auto">会員情報</a>
              {% endif %}
          </div>
      </div>
  </header>

    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

coffeemarket/market/templates/buying_error.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-10 offset-md-1 ml-3">
            <h3>購入失敗</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-10 offset-md-1"><p class="text-center">決済に失敗しました。<br>限度額に達しているか、カードの情報が正しいか確かめてください。<br><a href="mailto:akane.hoashi&#64gmail.com">問い合わせはこちらまで</a></p></div>
    </div>
</div>
{% endblock %}

coffeemarket/market/templates/buying_success.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-10 offset-md-1 ml-3">
            <h3>購入成功</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-md-10 offset-md-1"><p class="text-center">決済に成功しました。<br><a href="{% url 'market:top' %}">トップへ戻る</a></p></div>
    </div>
</div>
{% endblock %}

coffeemarket/market/templates/cart_info.html
{% extends 'base.html' %}

{% block content %}
{% load market_tags %}
<body>
<div class="container">
    <div class="row pt-5">
        <div class="col-md-10 offset-md-1">
            <h3 class="text text-secondary">カート情報</h3>
<!--            <div class="float-right text text-primary">{{ msg }}</div>-->
        </div>
    </div>
</div>
<div class="container">
    <div class="row pt-3">
        <div class="col-md-10 offset-md-1">
            <table class="table">
                <thread>
                    <tr>
                        <th>#</th>
                        <th>珈琲豆</th>
                        <th>数量</th>
                        <th>単価（100g)</th>
                        <th>金額</th>
                    </tr>
                </thread>
                <tbody>
                {% for cart_info in cart_info_list %}
                    <tr>
                        <th>{{ forloop.counter }}</th>
                        <td><a href="{% url 'market:beanDetail' cart_info.coffee_beans.pk %}" />{{ cart_info.coffee_beans.beans_name }}</td>
                        <td>{{ cart_info.volume }}</td>
                        <td>{{ cart_info.coffee_beans.price }}円</td>
                        <td>{{ cart_info.coffee_beans.price | sum_price:cart_info.volume }}円</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-10">
            {% if user.is_authenticated %}
                <form action="{% url 'market:buyingProcess' %}" method="POST">
                    <script
                        src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                        data-key="{{ public_key }}"
                        data-name="クレジット決済"
                        data-locate="ja"
                        data-currency="jpy"
                        data-label="カートで支払う"
                    >
                    </script>
                    {% csrf_token %}
                </form>
            {% endif %}
        </div>
    </div>

</div>
</body>
{% endblock %}

coffeemarket/market/templates/coffeebean_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row pt-5">
        <div class="col-md-12">
            <h3 class="float-left text text-secondary">商品情報</h3>
            <div class="float-right text text-primary">{{ msg }}</div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row mt-4">
        <div class="col-md-1"></div>
        <div class="p-0 col-md-4 shadow-sm">
            {% load static %}
            <img  src="{% static 'market/bean.jpg' %}" style="width:100%; height:100%;">
        </div>
        <div class="col-md-6 mt-3 shadow-sm">
            <h5 class="ml-4">{{ coffee_bean.beans_name }}</h5>
            <div class="ml-5 text-secondary">原産地：{{ coffee_bean.place_category }}</div>
            <div class="text-danger ml-5">￥{{ coffee_bean.price }}/100グラム</div>
            {% if user.is_authenticated %}
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group col-md-3 mb-0">
                        {{ insert_cart }}
                    </div>
                    <button type="submit" class="mb-2 float-right btn btn-primary">カートへ追加</button>
                </form>
            {% endif %}
        </div>
    </div>
</div>
<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <h3 class="text text-secondary">
                紹介文
            </h3>
        </div>
    </div>
    <div class="row ">
        <div class="p-0 offset-md-1 col-md-10">
            <p class="text text-secondary ">
                {{ coffee_bean.beans_description }}
            </p>
        </div>
    </div>
</div>
{% endblock %}

coffeemarket/market/templates/coffeebeans_form.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1 ml-3">
            <h3 class="text-primary">珈琲豆追加</h3>
        </div>
    </div>
    <form method="POST">
        {% csrf_token %}
        <div class="col-md-8 offset-md-2">
            <p class="text-right text-danger">{{ msg }}</p>
            <div class="form-group">
                <label for="id_beans_name">珈琲豆名</label>
                {{ form.beans_name}}
            </div>
            <div class="form-group">
                <label for="id_place_category">採取地</label>
                <label class="float-right" for="id_place_category"><a data-toggle="modal" data-target="#placeModal" href="#">採取地の登録</a></label>
                {{ form.place_category}}
            </div>
            <div class="form-group">
                <label for="id_price">値段</label>
                {{ form.price}}
            </div>
            <div class="form-group">
                <label for="id_stock">在庫数</label>
                {{ form.stock}}
            </div>
            <div class="form-group">
                <label for="id_beans_description">説明</label>
                {{ form.beans_description}}
            </div>
            <div class="col-md-10 offset-md-1 mt-5">
                <button type="submit" class="col-md-12 btn btn-lg btn-primary mx-auto">送信</button>
            </div>
        </div>
    </form>
    <div class="modal fade" id="placeModal" tabindex="-1" role="dialog" aria-labelledby="placeModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="placeModalLabel">採取地の登録</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            </button>
          </div>
          <form action="{% url 'market:insertPlace' %}" method="post">
          <div class="modal-body">
                {% csrf_token %}
              <div class="form-group">
                <label for="insert_place" class="col-form-label">採取地の入力をしてね</label>
                <input type="text" class="form-control" id="insert_place" name="place"></input>
              </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
            <button type="submit" class="btn btn-primary">送信</button>
          </div>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}
</html>

coffeemarket/market/templates/complete.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>登録完了ページ</title>
</head>
<body>
<p>{{ message }}</p>
</body>
</html>

coffeemarket/market/templates/create_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>新規作成</title>
</head>
<body>
<header>
    <h3>新規会員登録</h3>
</header>
<article>
<form method="post" action="">
    {% csrf_token %}
    {{ form }}
    <button type="submit">登録！！</button>
</form>
</article>
</body>
</html>

coffeemarket/market/templates/purchase_history.html
{% extends 'base.html' %}

{% block content %}
{% load market_tags %}
<body>
<div class="container">
    <div class="row pt-5">
        <div class="col-md-12">
            <h3 class="float-left text text-secondary">購入詳細</h3>
            <div class="float-right text text-primary">{{ msg }}</div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row mt-4">
        <div class="col-md-10 offset-md-1">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">購入日時</th>
                        <th scope="col">合計金額</th>
                        <th scope="col">決済方法</th>
                    </tr>
                </thead>
                <tbody>
                    {% for purchase_history in purchase_historys %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <th scope="row"><a href="{% url 'market:purchaseHistoryDetail' purchase_history.pk %}">{{ purchase_history.buy_date }}</th>
                        <td scope="row">{{ purchase_history.total_price }}</td>
                        <td scope="row">{{ purchase_history.payment_code.payment_method}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
</body>
{% endblock %}
</html>

coffeemarket/market/templates/top.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-10 offset-md-1 ml-3">
            <h3>お好きな商品を選択してください。</h3>
        </div>
    </div>
    {% for coffee_bean in coffee_beans %}
    <div class="row mt-4 pt-2 rounded">
        <div class="card mb-3 p-0 col-md-10 offset-md-2 shadow-sm" style="max-width: 700px">
            <div class="row no-gutters">
                <div class="col-md-4 my-auto">
                    {% load static %}
                    <img class="card-img" src="{% static 'market/bean.jpg' %}" style="width:230px; height:150px;">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title text-center">{{ coffee_bean.beans_name }}</h5>
                        <div class="text-danger text-center">￥{{ coffee_bean.price }}</div>
                        <a class="btn btn-primary float-right mt-3" href="{% url 'market:beanDetail' coffee_bean.pk %}">詳細</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

coffeemarket/market/templates/user_info.html
{% extends 'base.html' %}
{% block content %}
<article>
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-10 offset-md-1">
                <div class="card-deck">
                    <div class="card border-0 p-0">
                        <a href="{% url 'accounts:userInfo' %}" class="text-secondary card-body btn btn-outline-success">
                            会員情報変更<br>
                            <small class="text-muted">・会員情報の閲覧、変更できます。</small>
                        </a>
                    </div>
                    <div class="card border-0 p-0">
                        <a href="{% url 'market:purchaseHistory' %}" class="text-secondary card-body btn btn-outline-success">
                            購入履歴一覧<br>
                            <small class="text-muted">・購入履歴を閲覧できます。</small>
                        </a>
                    </div>
                    <div class="card border-0 p-0">
                        <a href="#" class="text-secondary card-body btn btn-outline-success">
                            退会<br>
                            <small class="text-muted">・退会します。</small>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</article>
{% endblock %}